### ISSUE TITLE
Python 2 is a requirement?

### ISSUE THREAD

**Issue by lachlansimpson** [OpenGene/AfterQC#21]
I installed this in a venv with Python3 and got:

``` [root@vmpr-res-head-node ~]# after.py 
  Traceback (most recent call last):
  File "/config/binaries/afterqc/0.9.2/afterqc/after.py", line 7, in <module>
    import preprocesser
  File "/config/binaries/afterqc/0.9.2/afterqc/preprocesser.py", line 8, in <module>
    import util
  File "/config/binaries/afterqc/0.9.2/afterqc/util.py", line 167
    print overlap(r1, r2)
```

which I presume is a python3 thing. 

You should note that python2 is a requirement in the install notes.

**Comment by sfchen** [comment]
Thanks, I will update the requirement.

**Comment by sfchen** [comment]
Added a hit for python3:

"python3 is not supported yet, please use python2"

Since python2 has much better support for PyPy, AfterQC will continue use python2.

Closing this issue.
