### ISSUE TITLE
Issue with overlap analysis

### ISSUE THREAD

**Issue by ghost** [OpenGene/AfterQC#34]
Hi, 

I'm working on SRA data (SRR4292097). I get the following error
`after.py
specify current dir as input dir
SRR4292097_R1.fastq.gz
./SRR4292097_R1.fastq.gz options:
{'read1_file': './SRR4292097_R1.fastq.gz', 'read2_file': './SRR4292097_R2.fastq.gz', 'index1_file': None, 'index2_file': None, 'input_dir': '.', 'good_output_folder': 'good', 'bad_output_folder': None, 'report_output_folder': None, 'read1_flag': 'R1', 'read2_flag': 'R2', 'index1_flag': 'I1', 'index2_flag': 'I2', 'trim_front': 8, 'trim_tail': 0, 'trim_pair_same': True, 'qualified_quality_phred': 15, 'unqualified_base_limit': 60, 'poly_size_limit': 35, 'allow_mismatch_in_poly': 2, 'n_base_limit': 5, 'seq_len_req': 35, 'debubble': False, 'debubble_dir': 'debubble', 'draw': True, 'barcode': False, 'barcode_length': 12, 'barcode_flag': 'barcode', 'barcode_verify': 'CAGTA', 'store_overlap': False, 'overlap_output_folder': None, 'qc_only': False, 'qc_sample': 200000, 'qc_kmer': 8, 'no_correction': False, 'mask_mismatch': False, 'no_overlap': False, 'version': '0.9.6', 'trim_front2': 8, 'trim_tail2': 0}
Process Process-1:
Traceback (most recent call last):
  File "/home/XX/Softs/miniconda3/lib-python/2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/XX/Softs/miniconda3/lib-python/2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/XX/Softs/miniconda3/envs/py27/bin/after.py", line 171, in processOptions
    filter.run()
  File "/home/XX/Softs/miniconda3/envs/py27/share/afterqc-0.9.6-0/preprocesser.py", line 512, in run
    overlap_histgram[overlap_len] += 1
IndexError: list index out of range
Time used: 16.7429320812
`

Everything is working fine with the option --no_overlap.

Thanks,
Maxime

**Comment by sfchen** [comment]
Hi, I will test with SRR4292097, thanks.

**Comment by sfchen** [comment]
BTW, you can try fastp: https://github.com/OpenGene/fastp

fastp is re-implementation of AfterQC in C++, with more functions.

**Comment by ghost** [comment]
Hi, I tried with fastp, it perfectly works ! but it seems that there is not the afterQC "automatic trimming according to QC results" step? maybe I miss something in the command options?

Thanks,
Maxime

**Comment by sfchen** [comment]
Yes, fastp doesn't implement automatic trimming (may be implemented in coming releases).

For Illumina data, you can specify `-t 1` to trim the last one cycle.
